<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9UB8IQF" failures="0" tests="5" name="testNGKeywords.TimeOut" time="0.563" errors="1" timestamp="2022-11-19T04:07:03 CST" skipped="1">
  <testcase classname="testNGKeywords.TimeOut" name="B" time="0.014"/>
  <system-out>
    <![CDATA[Method B is running]]>
  </system-out>
  <testcase classname="testNGKeywords.TimeOut" name="C" time="0.326">
    <error message="Method testNGKeywords.TimeOut.C() didn&#039;t finish within the time-out 300" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGKeywords.TimeOut.C() didn't finish within the time-out 300
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- C -->
  <system-out/>
  <testcase classname="testNGKeywords.TimeOut" name="A" time="0.000">
    <skipped/>
  </testcase> <!-- A -->
  <system-out/>
  <testcase classname="testNGKeywords.TimeOut" name="D" time="0.011"/>
  <system-out>
    <![CDATA[Method D is running]]>
  </system-out>
  <testcase classname="testNGKeywords.TimeOut" name="E" time="0.212"/>
  <system-out>
    <![CDATA[Method E is running]]>
  </system-out>
</testsuite> <!-- testNGKeywords.TimeOut -->
